### ISSUE TITLE
Naming things

### ISSUE THREAD

**Issue by amotl** [owntracks/ocli#6]
As you might have seen through https://github.com/owntracks/ocli/pull/4#issuecomment-574727423, I deliberately chose to give this package the more verbose name `owntracks-publisher`. However, I've yet kept the binary name to `ocli`.

The idea behind that is to ease mental load on people running the whole OwnTracks software stack and to make it more clear to bystanders looking at some arbitrary `ps axf` output showing which processes are actually running on the machine and what they mean.

From this perspective, I found `ocli` to be a bit too short. However, we might think about keeping it as an alias?

Feel free to reject this right away if you like it to stay `ocli` (period) ;]. I don't want to step on anyones toes with my ramblings.

**Comment by amotl** [comment]
I also want to mention that I was a bit unsure what to expect from that program when recognizing it just recently. First, I thought it would be a CLI program for accessing `owntracks-recorder` on the read path.

Naming it something like `publisher` would make that detail totally clear.

So, I just wanted to share my thoughts here. Please don't mind if this does not resonate with you.

**Comment by jpmens** [comment]
Let's settle for `owntracks-cli-publisher` then for the `ps ax` output. Maybe one day there'll be a different publisher, and I hope this makes it clear it's a _cli_-type, i.e. simple,  utility with very few frills.

**Comment by amotl** [comment]
All right.

1. I will update the package name and will leave renaming the program itself up to you. Please adjust the packaging script then within [1].

2. We might also consider updating the repository name as well.

[1] https://github.com/owntracks/ocli/blob/0.8.0/packaging/builder/fpm-package#L45-L46
